version: "3.9"

services:
  wordpress:
    image: wordpress:latest
    # using volumes only during development
    # volumes:
    #   - .:/var/www/html
    ports:
      - "$PORT:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
