version: "3.9"

# This is only for development purposes.
services:
  mysql:
    image: mysql:5.7
    container_name: developerswork-wp-mysql
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $WORDPRESS_DB_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD

  wordpress:
    depends_on:
      - mysql
    image: wordpress_workspace
    container_name: developerswork-wp-workspace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - .:/var/www/html
    ports:
      - "80:80"
      - "8080:8080"
      - "3000:3000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG
